### ISSUE TITLE
Backbone 1.2.0 support

### ISSUE THREAD

**Issue by kusmierz** [rotundasoftware/backbone.subviews#24]
Currently you have `"backbone": "~1.1.0"` in your `dependencies` section in bower.json file. Is it possible to update it to `>=1.1.0,1.*` for example?

**Comment by dgbeck** [comment]
Hi @kusmierz . Thanks! Done in v0.7.4.

**Comment by kusmierz** [comment]
Great, thanks!

**Comment by kusmierz** [comment]
How could I download v0.7.4? Or when?
